services:
  app:
    container_name: blog
    build: .
    ports:
     - "3000:3000"
    restart: always
    networks:
      - reverse_proxy_default

networks:
  reverse_proxy_default:
    external: true